#!/bin/bash

# ──────────────────────────────────────────────────────────────────────
# - Automatic DJ Message Clear Script for Purple Radio - Durham
# - Designed to refresh DJ message cache at show boundaries
# - Dependencies: curl, jq, date
# ──────────────────────────────────────────────────────────────────────

# ──────────────────────────────────────────────────────────────────────
# - Variables
# ──────────────────────────────────────────────────────────────────────

authToken=""
apiEndpoint="radio.purpleradio.co.uk/api/live-info-v2"

# ──────────────────────────────────────────────────────────────────────     
# - Core Loop
# ──────────────────────────────────────────────────────────────────────     

while true; do

    # ╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶
    # - Get schedule info   
    # ╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶

    currentTimestamp=$(date +"%s")
    response=$(curl -s --request GET "$apiEndpoint")

    nextStart=$(date --date="$(echo $response | jq -r ".nextShow[].start_timestamp")" +"%s")
    length=$(($nextStart - $currentTimestamp))
	
    # ╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶ 
    # - Sleep till start of next show
    # ╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶ 
    
    sleep $length

    # ╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶ 
    # - Clear DJ Messages
    # ╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶╶ 

    curl -X "DELETE" https://api.purpleradio.co.uk/purple-radio/deleteAllMessages/$authToken

done

